POST http://localhost:3001/api/kaynnit
Content-Type: application/json

{
    "kavija": "asynckavija!!!",
    "satama": "satama3",
    "laiva": "laiva3",
    "palvelut": ["palvelu2","palvelu4"],
    "toimitukset": ["toimitus2", "toimitus4"],
    "kesto": 15,
    "henkiloiden_maara": 5,
    "keskustelujen_maara": 5,
    "kuljetettujen_maara": 2,
    "merenkulkijoiden_viesti": "viesti",
    "mepan_viesti": "mepaviesti" 
}