POST http://localhost:3001/api/kaynnit
Content-Type: application/json

{
    "kayttaja": "kayttaka",
    "kavijat": ["asynckavija???", "async2"],
    "satama": "satama3",
    "laivaId": 50,
    "palvelut": ["palvelu2","palvelu4"],
    "toimitukset": ["toimitus2", "toimitus4"],
    "kesto": 15,
    "henkiloiden_maara": 5,
    "keskustelujen_maara": 5,
    "kuljetettujen_maara": 2,
    "merenkulkijoiden_viesti": "viesti",
    "mepan_viesti": "mepaviesti" 
}